<?php

namespace AppBundle\Repository;

/**
 * SubscriberADKCampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberADKCampaignRepository extends \Doctrine\ORM\EntityRepository
{
}
